# GCP ProviderConfig with service account secret reference
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: rd-platform-crossplane-dev
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: default-gcp-credentials
      key: credentials.json