apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: deployments/crossplane
    repoURL: 'https://github.com/david-behnke/config-local.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: default
  ignoreDifferences:
  - group: "*"
    kind: "ClusterRole"
    jsonPointers:
      - /rules
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true

